src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BBC_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>BBC ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Action__c.object
<CustomObject>
    <description>This object is used to track actions performed by end users</description>
    <fields>
        <fullName>Action_Date__c</fullName>
        <label>Action Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Action_Name__c</fullName>
        <label>Action Name</label>
        <picklist>
            <picklistValues>
                <fullName>Change email-address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Set marketing preference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reset password</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel pre-order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add entitlements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remove entitlements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add credit card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remove credit card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add Store credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remove Store credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full refund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial refund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refund Store credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Get escalation update</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Actions</relationshipLabel>
        <relationshipName>Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <picklist>
            <controllingField>Action_Name__c</controllingField>
            <picklistValues>
                <fullName>Found the product cheaper elsewhere</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Changed their mind</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dissatisfied with product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Encountered technical issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TBC by BBC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical error online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Didn&apos;t know how to do it online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thought it would be faster to change via contact centre than online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(opt-in) Wants to receive marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(opt-in) Wants marketing but is not receiving it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(opt-out) Receives too much marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(opt-out) Didn&apos;t sign up for marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(opt-out) Felt the marketing wasn&apos;t appropriate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content not visible in My Programmes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restoring entitlements from a closed Store account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content has been refunded but is still visible in My Programmes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>User has an entitlement that they shouldn’t be entitled to</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit was issued but refund is required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit was issued in error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Encountered issues redeeming credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up with case team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unclear on next steps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not had feedback within a period of time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Problem persists/is worsening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good-will gesture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product refund</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Action</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Action ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Getting started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manage your account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Using the service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing, vouchers and promotions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid Case</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Test_GEN_Action_BeforeInsUpdTrigger.cls
/* ----------------------------------------------------------------------------------------------------------------------------------------------------------

   Name:          GEN_Action_InsertUpdate_ActivityTrigger.Trigger

   Description:  Test class for GEN_Action_InsertUpdate_ActivityTrigger

                                                                       

   Date             Version             Author                                Summary of Changes

   -----------      ----------      -----------------                 ---------------------------------------------------------------------------------------------------

   Dec 2014            1.0             Masthan Vali Patnam                    Initial Release

------------------------------------------------------------------------------------------------------------------------------------------------------------ */

@isTest

Public class Test_GEN_Action_BeforeInsUpdTrigger{

  Static testmethod void TestInsetUpdateTrg(){
  
        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Case; 
        map<String,Schema.RecordTypeInfo> AccountRecordTypeInfo = cfrSchema.getRecordTypeInfosByName();
        List<Account> accLst=new List<Account>();

        Account acc=new Account();
        acc.BBC_ID__c = 'BBC0003';
        acc.PersonEmail = 'test@gmail.com';
        acc.LastName = 'testlastname';
        accLst.add(acc);
        insert accLst;

        List<Contact> conLst=new List<Contact>();
        contact con = new contact();
        con.lastname = 'lastname';
        con.AssistantName = acc.Id;
          
        conLst.add(con);
        insert conLst;

        List<Case> casLst = new List<Case>();

        case cas= new case();

        cas.RecordTypeId = AccountRecordTypeInfo.get('Community Case').getRecordTypeId();
        cas.Status = 'New';
        cas.contactId= con.id;
        cas.Category__c = 'Getting started';

        casLst.add(cas);
        insert casLst; 

        List<Action__C> actnLst=new List<Action__C>();
        Date dt=Date.today();
        Action__C actn=new Action__C();
        actn.Action_Name__c = 'Change email-address';
        actn.Status__c = 'Pending';
        actn.Case__c = cas.Id;
        actn.Action_Date__c = dt.addDays(-2);   
        actn.Description__c = 'Description';
        actn.Reason__c = 'Bought product elsewhere';
        actnLst.add(actn);

        insert actnLst;
    
  }

}