src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BBC_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>BBC ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Action__c.object
<CustomObject>
    <description>This object is used to track actions performed by end users</description>
    <fields>
        <fullName>Action_Date__c</fullName>
        <label>Action Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Action_Name__c</fullName>
        <label>Action Name</label>
        <picklist>
            <picklistValues>
                <fullName>Change email-address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Set marketing preference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reset password</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel pre-order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add entitlements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remove entitlements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add credit card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remove credit card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add Store credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remove Store credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full refund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial refund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refund Store credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Get escalation update</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Actions</relationshipLabel>
        <relationshipName>Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <picklist>
            <controllingField>Action_Name__c</controllingField>
            <picklistValues>
                <fullName>Found the product cheaper elsewhere</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Changed their mind</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dissatisfied with product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Encountered technical issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TBC by BBC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical error online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Didn&apos;t know how to do it online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thought it would be faster to change via contact centre than online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(opt-in) Wants to receive marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(opt-in) Wants marketing but is not receiving it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(opt-out) Receives too much marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(opt-out) Didn&apos;t sign up for marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(opt-out) Felt the marketing wasn&apos;t appropriate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content not visible in My Programmes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restoring entitlements from a closed Store account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content has been refunded but is still visible in My Programmes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>User has an entitlement that they shouldn’t be entitled to</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit was issued but refund is required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit was issued in error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Encountered issues redeeming credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up with case team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unclear on next steps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not had feedback within a period of time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Problem persists/is worsening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good-will gesture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product refund</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Action</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Action ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Getting started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manage your account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Using the service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing, vouchers and promotions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid Case</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TEST_DigitalLockerController.cls
/* ----------------------------------------------------------------------------------------------------------------------------------------------------------

   Name:          TEST_DigitalLockerController.cls

   Description:  Test class for GEN_DigitalLockerController

                                                                       

   Date             Version        Author                                Summary of Changes

   -----------      ----------      -----------------                 ---------------------------------------------------------------------------------------------------

   Dec 2014     1.0        Shalabh Sharma                               Initial Release

------------------------------------------------------------------------------------------------------------------------------------------------------------ */

@isTest(seeAllData=true)

private class TEST_DigitalLockerController
{
    static Account accountRecord = new Account();
    static Contact contactRecord = new Contact();
    static Case caseRecord = new Case();
    static Action__c actionRecord = new Action__c();

    static void createTestData(){

        RecordType rtAcc = [Select Id from RecordType where Name='Account'];
        
        accountRecord.BBC_ID__c = '12345';
        accountRecord.Name = 'TESTACCOUNT';
        //accountRecord.PersonEmail = 'test@test.com';
        accountRecord.RecordTypeId = rtAcc.Id;

        insert accountRecord;
    
        contactRecord.LastName = 'TESTCONTACT';
        contactRecord.AccountId = accountRecord.Id;
        insert contactRecord;

        RecordType rtCs = [Select Id from RecordType where Name='Community Case'];
        caseRecord.ContactId = contactRecord.Id;
        caseRecord.Status = 'In Progress';
        caseRecord.Category__c = 'Getting started';
        caseRecord.Origin = 'Community';
        caseRecord.RecordTypeId = rtCs.Id;
        insert caseRecord;

        RecordType rtAct = [Select Id from RecordType where Name='Action Record Type'];
        actionRecord.Action_Name__c = 'Cancel pre-order';
        actionRecord.Action_Date__c = System.Today();
        actionRecord.Status__c = 'Pending';
        actionRecord.Case__c = caseRecord.Id;
        actionRecord.RecordTypeId = rtAct.Id;
        actionRecord.Description__c  = 'TESTACTION';
        actionRecord.Reason__c = 'Bought product elsewhere';
        insert actionRecord;        
    }

    static testMethod void testDigitalLocker(){
        Test.startTest();
        createTestData();
        
        //Commented the code as Digital Locker is not going in this sprint so uncomment the code in next sprint to cover GEN_DigitalLockerController class
        /*ApexPages.currentPage().getParameters().put('Id', caseRecord.Id);
        
        GEN_DigitalLockerController controller = new GEN_DigitalLockerController();
        controller.newSearchText = actionRecord.Name;
        controller.getProducts();
        controller.getReasonValues();
        controller.remove();
        controller.getAddProducts();
        GEN_DigitalLockerController.createAction(actionRecord.Reason__c,actionRecord.Description__c,caseRecord.Id,accountRecord.Id);
        controller.back();
        controller.addEntitlements();
        controller.selected();
        controller.redirectToAction();
        controller.first();
        controller.last();
        controller.previous();
        controller.next();
        controller.searchProducts();*/
        Test.stopTest();
    }
}