src/objects/Action__c.object
<CustomObject>
    <description>This object is used to track actions performed by end users</description>
    <fields>
        <fullName>Action_Date__c</fullName>
        <label>Action Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Action_Name__c</fullName>
        <label>Action Name</label>
        <picklist>
            <picklistValues>
                <fullName>Change email-address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Set marketing preference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reset password</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel pre-order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add entitlements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remove entitlements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add credit card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remove credit card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add Store credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remove Store credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full refund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial refund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refund Store credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Get escalation update</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <picklist>
            <controllingField>Action_Name__c</controllingField>
            <picklistValues>
                <fullName>Found the product cheaper elsewhere</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Changed their mind</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dissatisfied with product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Encountered technical issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TBC by BBC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical error online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Didn&apos;t know how to do it online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thought it would be faster to change via contact centre than online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(opt-in) Wants to receive marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(opt-in) Wants marketing but is not receiving it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(opt-out) Receives too much marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(opt-out) Didn&apos;t sign up for marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(opt-out) Felt the marketing wasn&apos;t appropriate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content not visible in My Programmes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restoring entitlements from a closed Store account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content has been refunded but is still visible in My Programmes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>User has an entitlement that they shouldn’t be entitled to</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit was issued but refund is required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit was issued in error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Encountered issues redeeming credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up with case team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unclear on next steps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not had feedback within a period of time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Problem persists/is worsening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good-will gesture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product refund</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Action</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Action ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GEN_PaymentInformation_Ctrl.cls
global with sharing class GEN_PaymentInformation_Ctrl {
    
    public list<selectOption> range {get; set;}
    public list<selectOption> pType {get; set;}
    private String initialsortField = 'Name';
    public String sortDir {
        // To set a Direction either in ascending order or descending order.
                                get  { if (sortDir == null) {  sortDir = 'asc'; } return sortDir;}
        set;
    }
    public String sortField {get; set;}
    
    public Integer countPage{get;set;}
    
    
    
    
    List<GEN_ProductWrapper> products {get;set;}
    public Integer countProd{get;set;}
    public String caseId;
    public Boolean noRecordSelected{get;set;}
    public Case caseRecord{get;set;}
    public String actionStatus{get;set;}

    // instantiate the StandardSetController from a query locator
    public ApexPages.StandardSetController con {
        get {
            if(con == null) {
                con = new ApexPages.StandardSetController(Database.getQueryLocator([Select Id, Name, Action_Name__c, Action_Date__c, Reason__c,Status__c FROM Action__c Order By Action_Date__c DESC limit 100]));
                // sets the number of records in each page set
                con.setPageSize(10);
                list<Action__c> l = new list<Action__c>();
                l = [Select Id, Name, Action_Name__c, Action_Date__c, Reason__c,Status__c FROM Action__c Order By Action_Date__c DESC limit 100];
                countPage = l.size();
            }
            return con;
        }
        set;        
    }

   public GEN_PaymentInformation_Ctrl() {
        range = new list<selectoption>();
        pType = new list<selectoption>();
        range.add(new selectoption('Last 7 days','Last 7 days'));
        range.add(new selectoption('Last 14 days','Last 14 days'));
        range.add(new selectoption('Last 30 days','Last 30 days'));
        range.add(new selectoption('AllTime','AllTime'));
        pType.add(new selectoption('select Payment type','select Payment type'));
        pType.add(new selectoption('Credit Card','Credit Card'));
        
        
        
        //initialize variables


        caseId = ApexPages.currentPage().getParameters().get('caseId');
        caseRecord = [Select Id, CaseNumber, AccountId from Case where Id=:caseId];

        
    }

    // returns a list of wrapper objects for the sObjects in the current page set
    public List<GEN_ProductWrapper> getProducts() {
        products = new List<GEN_ProductWrapper>();
        for (Action__c prod : (List<Action__c>)con.getRecords())
            products.add(new GEN_ProductWrapper(prod));
        return products;
    }





    // displays the selected items
     public PageReference selected() {
         
         return null;
     }


    // indicates whether there are more records after the current page set.
    public Boolean hasNext {
        get {
            return con.getHasNext();
        }
        set;
    }

    // indicates whether there are more records before the current page set.
    public Boolean hasPrevious {
        get {
            return con.getHasPrevious();
        }
        set;
    }

    // returns the page number of the current page set
    public Integer pageNumber {
        get {
            return con.getPageNumber();
        }
        set;
    }

    // returns the first page of records
     public void first() {
         con.first();
     }

     // returns the last page of records
     public void last() {
         con.last();
     }

     // returns the previous page of records
     public void previous() {
         con.previous();
     }

     // returns the next page of records
     public void next() {
         con.next();
     }
    // returns the PageReference of the original page, if known, or the home page.
     public PageReference back() {
         return new PageReference('/'+caseId);
     }



     
     public class GEN_ProductWrapper {

     public Boolean checked{ get; set; }
     public Action__c prod { get; set;}

         public GEN_ProductWrapper(Action__c p){
             prod = p;
             checked = false;
        }
    }
    
    public pageReference sortList(){
    	try{
	    	sortDir = sortDir.equals('asc') ? 'desc' : 'asc';
	    	string qry = 'Select Id, Name, Action_Name__c, Action_Date__c, Reason__c,Status__c FROM Action__c order by '+sortField+' '+sortDir+ ' limit 100';
	    	system.debug('Query----->'+qry);
	    	con = new ApexPages.StandardSetController(Database.getQueryLocator(qry));
	    	con.setPageSize(10);
	    	list<Action__c> l = new list<Action__c>();
	        l = database.query(qry);
	        countPage = l.size();
    	}catch(exception e){
    		system.debug(e.getMessage());
    	}
		return null;    	
    }
    


}