src/objects/Action__c.object
<CustomObject>
    <description>This object is used to track actions performed by end users</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Actions</relationshipLabel>
        <relationshipName>Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Action_Date__c</fullName>
        <label>Action Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Action_Name__c</fullName>
        <label>Action Name</label>
        <picklist>
            <picklistValues>
                <fullName>Change email-address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Set marketing preference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reset password</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel pre-order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add entitlements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remove entitlements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add credit card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remove credit card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add Store credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remove Store credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full refund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial refund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refund Store credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Get escalation update</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Actions</relationshipLabel>
        <relationshipName>Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <picklist>
            <controllingField>Action_Name__c</controllingField>
            <picklistValues>
                <fullName>Found the product cheaper elsewhere</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Changed their mind</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dissatisfied with product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Encountered technical issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TBC by BBC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical error online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Didn&apos;t know how to do it online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thought it would be faster to change via contact centre than online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(opt-in) Wants to receive marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(opt-in) Wants marketing but is not receiving it</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(opt-out) Receives too much marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(opt-out) Didn&apos;t sign up for marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(opt-out) Felt the marketing wasn&apos;t appropriate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content not visible in My Programmes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Restoring entitlements from a closed Store account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Content has been refunded but is still visible in My Programmes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>User has an entitlement that they shouldn’t be entitled to</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit was issued but refund is required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit was issued in error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Encountered issues redeeming credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up with case team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unclear on next steps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not had feedback within a period of time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Problem persists/is worsening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good-will gesture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product refund</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Action</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Action ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ActionScreen__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>CS_ActionScreen</label>
</CustomObject>

src/classes/GEN_DigitalLockerController.cls
/* ----------------------------------------------------------------------------------------------------------------------------------------------------------

   Name:          GEN_DigitalLockerController.cls

   Description:  Controller for GEN_DigitalLocker page

                                                                       

   Date             Version        Author                                Summary of Changes

   -----------      ----------      -----------------                 ---------------------------------------------------------------------------------------------------

   Nov 2014     1.0        Shalabh Sharma                               Initial Release

------------------------------------------------------------------------------------------------------------------------------------------------------------ */

global with sharing class GEN_DigitalLockerController {

    List<GEN_ProductWrapper> products {get;set;}
    List<GEN_AddEntitlements> addProducts {get;set;}
    public Integer countProd{get;set;}
    public Boolean showAddEntitlement{get;set;}
    public Boolean showRemoveEntitlement{get;set;}
    public Boolean showCancelPreOrder{get;set;}
    public Integer countPage{get;set;}
    public String caseId;
    public Action__c action{get;set;}
    public String Reason{get;set;}
    public Boolean noRecordSelected{get;set;}
    public Case caseRecord{get;set;}
    public Boolean reasonNotSelected{get;set;}
    public String inputProduct{get;set;}
    public String actionStatus{get;set;}
    public String newSearchText;
    public Boolean showProd{get;set;}

    // instantiate the StandardSetController from a query locator
    public ApexPages.StandardSetController con {
        get {
            if(con == null) {
                con = new ApexPages.StandardSetController(Database.getQueryLocator([Select Id, Name, Action_Name__c, Action_Date__c, Reason__c FROM Action__c Order By Action_Date__c DESC limit 100]));
                // sets the number of records in each page set
                con.setPageSize(5);
                
            }
            return con;
        }
        set;        
    }

    public GEN_DigitalLockerController(){
        
        //initialize variables
        showAddEntitlement = false;
        showRemoveEntitlement = false;
        showCancelPreOrder = false;
        action = new Action__c();

        RecordType rt = [Select Id from RecordType where Name='Action Record Type'];
        action.RecordTypeId = rt.Id;
        
        //returns the total count of records
        countProd = [Select count() FROM Action__c limit 100];

        // return the total number of pages
        Double value = ((Double)countProd)/5;
        countPage = (Integer)((Decimal)value).round(System.RoundingMode.UP);

        caseId = ApexPages.currentPage().getParameters().get('caseId');
        system.debug('caseId--->'+caseId);
        if(caseId!=null)
        caseRecord = [Select Id, CaseNumber, AccountId from Case where Id=:caseId];

        //give Add Entitlement access to specific set of CSRs
        CustomPermission custPerAdd = [Select Id from CustomPermission WHERE DeveloperName='AddEntitlements'];
        Map<Id,PermissionSetAssignment> mapUserPerSetAdd = new Map<Id,PermissionSetAssignment>();
        mapUserPerSetAdd = getPermissions(custPerAdd.Id);
        if(!mapUserPerSetAdd.containsKey(UserInfo.getUserId()))
            showAddEntitlement = true;

        // give Remove Entitlement access to specific set of CSRs
        CustomPermission custPerRemove = [Select Id from CustomPermission WHERE DeveloperName='RemoveEntitlements'];
        Map<Id,PermissionSetAssignment> mapUserPerSetRemove = new Map<Id,PermissionSetAssignment>();
        mapUserPerSetRemove = getPermissions(custPerRemove.Id);
        if(!mapUserPerSetRemove.containsKey(UserInfo.getUserId()))
            showRemoveEntitlement = true;

        // give Cancel Pre-order access to specific set of CSRs
        CustomPermission custPerCancel = [Select Id from CustomPermission WHERE DeveloperName='CancelPreOrder'];
        Map<Id,PermissionSetAssignment> mapUserPerSetCancel = new Map<Id,PermissionSetAssignment>();
        mapUserPerSetCancel = getPermissions(custPerCancel.Id);
        if(mapUserPerSetCancel.containsKey(UserInfo.getUserId()))
            showCancelPreOrder = true;

        system.debug('showCancelPreOrder-->'+showCancelPreOrder);
        
        Map<String,ActionScreen__c> customSettingActionScreen = new Map<String,ActionScreen__c>();
        customSettingActionScreen = ActionScreen__c.getAll();
        actionStatus = customSettingActionScreen.values().Status__c;
    }

    // returns a list of wrapper objects for the sObjects in the current page set
    public List<GEN_ProductWrapper> getProducts() {
        products = new List<GEN_ProductWrapper>();
        for (Action__c prod : (List<Action__c>)con.getRecords())
            products.add(new GEN_ProductWrapper(prod));
        return products;
    }

    // return custom permission details
    public Map<Id,PermissionSetAssignment> getPermissions(String permissionId){
        Map<Id,PermissionSetAssignment> mapUserPerSetAssign = new Map<Id,PermissionSetAssignment>();
        for(PermissionSetAssignment objPerSet : [SELECT AssigneeId, PermissionSetId,
                                                PermissionSet.Label
                                                FROM PermissionSetAssignment
                                                WHERE PermissionSetId
                                                IN (SELECT ParentId
                                                   FROM SetupEntityAccess
                                                   WHERE SetupEntityType =
                                                'CustomPermission' AND SetupEntityId =: permissionId)]){
            if(objPerSet.AssigneeId != null)
            mapUserPerSetAssign.put(objPerSet.AssigneeId,objPerSet);          
        }
        return mapUserPerSetAssign;
    }

    // create picklist for Reason field
    public List<SelectOption> getReasonValues() {             
        return getPicklistFieldValues('Action__c','Reason__c');
    }

    // Private method to get picklist values from Objects
    private List<SelectOption> getPicklistFieldValues(String strObjectAPIName, String strFieldAPIName)
    {
        List<SelectOption> options = new List<SelectOption>();
        Schema.SObjectType targetType = Schema.getGlobalDescribe().get(strObjectAPIName);//From the Object Api name retrieving the SObject
        Sobject Object_name = targetType.newSObject();
        Schema.sObjectType objOppReg = Object_name.getSObjectType(); 
        Schema.DescribeSObjectResult objDescribe = objOppReg.getDescribe();       
        Map<String, Schema.SObjectField> mapFieldAndSchemaObject = objDescribe.fields.getMap(); 
        List<Schema.PicklistEntry> values = mapFieldAndSchemaObject.get(strFieldAPIName).getDescribe().getPickListValues();
        system.debug('values--->'+values);
        options.add(new SelectOption('','--None--'));
        for (Schema.PicklistEntry a : values)
        { 
            options.add(new SelectOption(a.getLabel(), a.getValue())); 
            
        }
            
        return options;
    }

    // insert action record
    @RemoteAction
    global static void createAction(String reason, String description, String caseId, String accountId){ 
            Action__c cancelOrder = new Action__c();
            cancelOrder.Reason__c = reason;
            cancelOrder.Description__c = description;
            cancelOrder.Action_Name__c = 'Cancel pre-order';
            cancelOrder.Case__c = caseId;
            cancelOrder.Account__c = accountId;
            cancelOrder.Status__c = 'Completed';
            cancelOrder.Action_Date__c = System.Today();

            insert cancelOrder;
    }

    // displays the selected items
     public PageReference selected() {
         
         return null;
     }

     public PageReference remove() {
         List<Action__c> lstSelectedEntitlements = new List<Action__c>();
         for(GEN_ProductWrapper prodWrap : products){
            if(prodWrap.checked == true){
                lstSelectedEntitlements.add(prodWrap.prod);
            }
         }
         system.debug('lstSelectedEntitlements-->'+lstSelectedEntitlements.size());
         if(lstSelectedEntitlements.size()==0){
             noRecordSelected = true;
         }
         else{
            noRecordSelected = false;
         }
         return null;
     }

    // indicates whether there are more records after the current page set.
    public Boolean hasNext {
        get {
            return con.getHasNext();
        }
        set;
    }

    // indicates whether there are more records before the current page set.
    public Boolean hasPrevious {
        get {
            return con.getHasPrevious();
        }
        set;
    }

    // returns the page number of the current page set
    public Integer pageNumber {
        get {
            return con.getPageNumber();
        }
        set;
    }

    // returns the first page of records
     public void first() {
         con.first();
     }

     // returns the last page of records
     public void last() {
         con.last();
     }

     // returns the previous page of records
     public void previous() {
         con.previous();
     }

     // returns the next page of records
     public void next() {
         con.next();
     }
    // returns the PageReference of the original page, if known, or the home page.
     public PageReference back() {
         return new PageReference('/'+caseId);
     }

     public PageReference addEntitlements(){
        return new PageReference('/apex/GEN_AddEntitlements');
     }

     //returns a list of products to add as entitlements
     public void searchProducts(){
        showProd = true;           
     }

     public List<GEN_AddEntitlements> getAddProducts(){
        newSearchText = '%'+inputProduct+'%';
        addProducts = new List<GEN_AddEntitlements>();
        for (Action__c prod : [Select Id, Name, Action_Date__c from Action__c where Name LIKE: newSearchText LIMIT 20])
            addProducts.add(new GEN_AddEntitlements(prod));
         return addProducts;    
     }

     public PageReference redirectToAction() {
        return new PageReference('/a00/o');
     }
     
     public class GEN_ProductWrapper {

     public Boolean checked{ get; set; }
     public Action__c prod { get; set;}

         public GEN_ProductWrapper(Action__c p){
             prod = p;
             checked = false;
        }
    }
     public class GEN_AddEntitlements
     {
        public Boolean selected{ get; set; }
        public Action__c addProducts { get; set;}

        public GEN_AddEntitlements(Action__c p){
            addProducts = p;
            selected = false;
        }
     }
}